// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DatabaseLicenseType.
const (
	Evaluation   DatabaseLicenseType = "evaluation"
	Redistribute DatabaseLicenseType = "redistribute"
	Standard     DatabaseLicenseType = "standard"
)

// Valid indicates whether the value is a known member of the DatabaseLicenseType enum.
func (e DatabaseLicenseType) Valid() bool {
	switch e {
	case Evaluation:
		return true
	case Redistribute:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseStanding.
const (
	DatabaseStandingExpired    DatabaseStanding = "expired"
	DatabaseStandingLicensed   DatabaseStanding = "licensed"
	DatabaseStandingUnlicensed DatabaseStanding = "unlicensed"
)

// Valid indicates whether the value is a known member of the DatabaseStanding enum.
func (e DatabaseStanding) Valid() bool {
	switch e {
	case DatabaseStandingExpired:
		return true
	case DatabaseStandingLicensed:
		return true
	case DatabaseStandingUnlicensed:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseFormatSizeFormat.
const (
	DatabaseFormatSizeFormatCsvgz DatabaseFormatSizeFormat = "csvgz"
	DatabaseFormatSizeFormatMmdb  DatabaseFormatSizeFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseFormatSizeFormat enum.
func (e DatabaseFormatSizeFormat) Valid() bool {
	switch e {
	case DatabaseFormatSizeFormatCsvgz:
		return true
	case DatabaseFormatSizeFormatMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseVersionSampleFormats.
const (
	DatabaseVersionSampleFormatsCsvgz DatabaseVersionSampleFormats = "csvgz"
	DatabaseVersionSampleFormatsMmdb  DatabaseVersionSampleFormats = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseVersionSampleFormats enum.
func (e DatabaseVersionSampleFormats) Valid() bool {
	switch e {
	case DatabaseVersionSampleFormatsCsvgz:
		return true
	case DatabaseVersionSampleFormatsMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DownloadOutcome.
const (
	DownloadOutcomeDenied       DownloadOutcome = "denied"
	DownloadOutcomeExpired      DownloadOutcome = "expired"
	DownloadOutcomeOk           DownloadOutcome = "ok"
	DownloadOutcomeUnauthorized DownloadOutcome = "unauthorized"
	DownloadOutcomeUnavailable  DownloadOutcome = "unavailable"
	DownloadOutcomeUnknown      DownloadOutcome = "unknown"
)

// Valid indicates whether the value is a known member of the DownloadOutcome enum.
func (e DownloadOutcome) Valid() bool {
	switch e {
	case DownloadOutcomeDenied:
		return true
	case DownloadOutcomeExpired:
		return true
	case DownloadOutcomeOk:
		return true
	case DownloadOutcomeUnauthorized:
		return true
	case DownloadOutcomeUnavailable:
		return true
	case DownloadOutcomeUnknown:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseChecksumParamsFormat.
const (
	DatabaseChecksumParamsFormatCsvgz DatabaseChecksumParamsFormat = "csvgz"
	DatabaseChecksumParamsFormatMmdb  DatabaseChecksumParamsFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DatabaseChecksumParamsFormat enum.
func (e DatabaseChecksumParamsFormat) Valid() bool {
	switch e {
	case DatabaseChecksumParamsFormatCsvgz:
		return true
	case DatabaseChecksumParamsFormatMmdb:
		return true
	default:
		return false
	}
}

// Defines values for DownloadDatabaseParamsFormat.
const (
	DownloadDatabaseParamsFormatCsvgz DownloadDatabaseParamsFormat = "csvgz"
	DownloadDatabaseParamsFormatMmdb  DownloadDatabaseParamsFormat = "mmdb"
)

// Valid indicates whether the value is a known member of the DownloadDatabaseParamsFormat enum.
func (e DownloadDatabaseParamsFormat) Valid() bool {
	switch e {
	case DownloadDatabaseParamsFormatCsvgz:
		return true
	case DownloadDatabaseParamsFormatMmdb:
		return true
	default:
		return false
	}
}

// ClassDetail The shared detail shape for the hosting, relay, tor and cdn datasets.
// Every key is present when the object is populated; the object is `{}`
// when its flag is false.
type ClassDetail struct {
	// Confidence How strongly the classification is supported.
	//
	// Example: high
	Confidence *string `json:"confidence,omitempty"`

	// LastSeen The most recent date this address was observed in this dataset.
	//
	// Example: 2026-09-02
	LastSeen *openapi_types.Date `json:"last_seen,omitempty"`

	// Provider The provider, or an empty string where the dataset has none.
	//
	// Example: m247
	Provider *string `json:"provider,omitempty"`
}

// Database One dataset FAMILY your organization is licensed for. A license covers
// the family, while a download names a specific version, so the ids you
// pass to the download and checksum endpoints come from `versions`.
type Database struct {
	// Base The dataset family, e.g. `vpn_ip`. What the license is held against.
	//
	// Example: vpn_ip
	Base string `json:"base"`

	// Expires A hard stop. Null when the license has no end date, which is the normal case for a rolling agreement, and when there is no license. A rolling license reports its turnover date in renews_at instead.
	Expires *time.Time `json:"expires"`

	// InTerm False when the license has lapsed; downloads are refused.
	InTerm bool `json:"in_term"`

	// LicenseType What your license permits you to do with the data.
	LicenseType DatabaseLicenseType `json:"license_type"`

	// Name Example: VPN IP
	Name string `json:"name"`

	// NoticeDueAt The last day notice of non-renewal can be given for the term ending at renews_at. Null whenever renews_at is, and when the agreement records no notice period.
	NoticeDueAt *time.Time `json:"notice_due_at"`

	// RenewsAt When a rolling license next renews. Null when the license has no defined term, when expires sets a hard stop instead, and when there is no license.
	RenewsAt *time.Time `json:"renews_at"`

	// Standing `licensed` is a live grant, `expired` one whose term has ended, and
	// `unlicensed` a dataset published but never bought.
	Standing DatabaseStanding `json:"standing"`
	Starts   *time.Time       `json:"starts"`
	Summary  string           `json:"summary"`

	// Versions Every published version of this family. The `id` here is what the
	// download and checksum endpoints take.
	Versions []DatabaseVersion `json:"versions"`
}

// DatabaseLicenseType What your license permits you to do with the data.
type DatabaseLicenseType string

// DatabaseStanding `licensed` is a live grant, `expired` one whose term has ended, and
// `unlicensed` a dataset published but never bought.
type DatabaseStanding string

// DatabaseFormatSize defines model for DatabaseFormatSize.
type DatabaseFormatSize struct {
	// Bytes Size of the published file, or null when it has not been published yet
	Bytes  *int                     `json:"bytes"`
	Format DatabaseFormatSizeFormat `json:"format"`
}

// DatabaseFormatSizeFormat defines model for DatabaseFormatSize.Format.
type DatabaseFormatSizeFormat string

// DatabaseMetadata defines model for DatabaseMetadata.
type DatabaseMetadata struct {
	// Entries Row count in the current build
	Entries int    `json:"entries"`
	ID      string `json:"id"`

	// Sample A few real rows, keyed by format
	Sample *map[string][]map[string]interface{} `json:"sample,omitempty"`

	// SampleEntries Row count in the evaluation sample
	SampleEntries *int `json:"sample_entries,omitempty"`

	// SampleSize Bytes per format of the evaluation sample, where one is published
	SampleSize *map[string]int `json:"sample_size,omitempty"`

	// Schema Columns, keyed by format
	Schema map[string][]DatabaseMetadataColumn `json:"schema"`

	// Size Bytes per format
	Size *map[string]int `json:"size,omitempty"`

	// UpdateFreq How often a new build is published
	UpdateFreq *string            `json:"update_freq,omitempty"`
	Updated    openapi_types.Date `json:"updated"`
}

// DatabaseMetadataColumn defines model for DatabaseMetadataColumn.
type DatabaseMetadataColumn struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
}

// DatabaseVersion defines model for DatabaseVersion.
type DatabaseVersion struct {
	Formats []DatabaseFormatSize `json:"formats"`

	// ID The versioned dataset id, e.g. `vpn_ip_v1`. Pass this to download.
	//
	// Example: vpn_ip_v1
	ID string `json:"id"`

	// SampleFormats The formats an evaluation sample is published in, if any.
	SampleFormats *[]DatabaseVersionSampleFormats `json:"sample_formats,omitempty"`
	Summary       *string                         `json:"summary,omitempty"`

	// Version Example: 1
	Version int `json:"version"`
}

// DatabaseVersionSampleFormats defines model for DatabaseVersion.SampleFormats.
type DatabaseVersionSampleFormats string

// DBChecksums The published digests for one database file.
type DBChecksums struct {
	Md5    string `json:"md5"`
	Sha1   string `json:"sha1"`
	Sha256 string `json:"sha256"`
	Sha512 string `json:"sha512"`
}

// Download One download ATTEMPT, refusals included - a denial is what answers "it
// stopped working", so they are listed rather than dropped.
type Download struct {
	// ApikeyID The key that made the request. Null when the org acted through the
	// console rather than through a key.
	ApikeyID *string `json:"apikey_id"`

	// Bytes Object size at redirect time, NOT bytes delivered: the transfer is a
	// presigned redirect straight to object storage, so we never observe it.
	Bytes      *int            `json:"bytes"`
	ClientIP   *string         `json:"client_ip"`
	Created    time.Time       `json:"created"`
	DatasetID  string          `json:"dataset_id"`
	Format     string          `json:"format"`
	HTTPStatus *int            `json:"http_status"`
	Outcome    DownloadOutcome `json:"outcome"`

	// Sample The evaluation sample rather than the database itself.
	Sample    bool    `json:"sample"`
	UserAgent *string `json:"user_agent"`
}

// DownloadOutcome defines model for Download.Outcome.
type DownloadOutcome string

// Error defines model for Error.
type Error struct {
	Rc string `json:"rc"`
}

// LookupError Every non-2xx response carries this shape.
type LookupError struct {
	// Error A human-readable explanation of the failure.
	//
	// Example: not a valid IP address
	Error string `json:"error"`
}

// LookupResponse The union of every plan's answer. Only `ip` and `is_vpn` are guaranteed;
// each remaining field is present when your plan includes it, and absent
// otherwise. A client that must work across plans should treat an absent
// flag as unknown rather than as `false`.
type LookupResponse struct {
	// Cdn Detail for `is_cdn`. Empty when false. Scale and above.
	Cdn *ClassDetail `json:"cdn,omitempty"`

	// Dcproxy Detail for `is_dcproxy`. Empty when false. Max only.
	Dcproxy *ProxyDetail `json:"dcproxy,omitempty"`

	// Hosting Detail for `is_hosting`. Empty when false. Scale and above.
	Hosting *ClassDetail `json:"hosting,omitempty"`

	// IP The address that was looked up, normalized.
	//
	// Example: 1.1.1.1
	IP string `json:"ip"`

	// IsCdn Whether the address belongs to a CDN. Starter and above.
	IsCdn *bool `json:"is_cdn,omitempty"`

	// IsDcproxy Whether the address was seen in a datacenter proxy pool. Scale and above.
	IsDcproxy *bool `json:"is_dcproxy,omitempty"`

	// IsHosting Whether the address belongs to a hosting or cloud provider. Starter and above.
	IsHosting *bool `json:"is_hosting,omitempty"`

	// IsMobproxy Whether the address was seen in a mobile proxy pool. Scale and above.
	IsMobproxy *bool `json:"is_mobproxy,omitempty"`

	// IsRelay Whether the address is a privacy relay egress. Starter and above.
	IsRelay *bool `json:"is_relay,omitempty"`

	// IsResproxy Whether the address was seen in a residential proxy pool. Scale and above.
	IsResproxy *bool `json:"is_resproxy,omitempty"`

	// IsTor Whether the address is a Tor node. Starter and above.
	IsTor *bool `json:"is_tor,omitempty"`

	// IsVpn Whether the address is VPN infrastructure. Keys off presence in the
	// VPN dataset, so an unattributed range with no provider is still
	// `true`.
	IsVpn bool `json:"is_vpn"`

	// Mobproxy Detail for `is_mobproxy`. Empty when false. Max only.
	Mobproxy *ProxyDetail `json:"mobproxy,omitempty"`

	// Relay Detail for `is_relay`. Empty when false. Scale and above.
	Relay *ClassDetail `json:"relay,omitempty"`

	// Resproxy Detail for `is_resproxy`. Empty when false. Max only.
	Resproxy *ProxyDetail `json:"resproxy,omitempty"`

	// Tor Detail for `is_tor`. Empty when false. Scale and above. The tor
	// dataset carries no provider, so `provider` is always an empty string.
	Tor *ClassDetail `json:"tor,omitempty"`

	// Vpn Detail for `is_vpn`. Empty when `is_vpn` is false. Starter and above.
	Vpn *VpnDetail `json:"vpn,omitempty"`
}

// ProxyDetail The shared detail shape for the residential, datacenter and mobile proxy
// families, measured over a rolling 90 day window. Every key is present
// when the object is populated; the object is `{}` when its flag is false.
type ProxyDetail struct {
	// FirstSeen The earliest date within the window this address was seen in the pool.
	//
	// Example: 2026-06-14
	FirstSeen *openapi_types.Date `json:"first_seen,omitempty"`

	// Hits How many times the address was observed in the pool during the window.
	//
	// Example: 42
	Hits *int `json:"hits,omitempty"`

	// HitsDaysPct The share of days in the window on which the address was seen, as a
	// percentage. A high value means a stable pool member rather than a
	// one-off sighting.
	//
	//
	// Example: 63
	HitsDaysPct *int `json:"hits_days_pct,omitempty"`

	// LastSeen The most recent date within the window this address was seen in the pool.
	//
	// Example: 2026-09-02
	LastSeen *openapi_types.Date `json:"last_seen,omitempty"`

	// Provider The proxy network, or an empty string where unattributed.
	//
	// Example: brightdata
	Provider *string `json:"provider,omitempty"`

	// ProvidersNum How many distinct proxy networks this address was seen in.
	//
	// Example: 2
	ProvidersNum *int `json:"providers_num,omitempty"`
}

// VpnDetail What is known about the VPN attribution. Every key is present when the
// object is populated, empty values included; the object is `{}` when
// `is_vpn` is false. `confidence` and `method` are max only, so on a lower
// plan they are absent from a populated object rather than empty.
type VpnDetail struct {
	// Confidence How strongly the attribution is supported. Max only.
	//
	// Example: high
	Confidence *string `json:"confidence,omitempty"`

	// LastSeen The most recent date this address was observed as VPN infrastructure.
	//
	// Example: 2026-09-02
	LastSeen *openapi_types.Date `json:"last_seen,omitempty"`

	// Method The class of evidence the attribution rests on, one of four values.
	// Max only.
	//
	// `scan` - we spoke the VPN protocol to the address ourselves and got a
	// valid server response. `scrape` - the operator published the address
	// through its own API, client or configuration. `registry` - public
	// registration or naming records attribute it to the operator.
	// `infer` - the address was extrapolated from confirmed neighbours in
	// the same block.
	//
	//
	// Example: scan
	Method *string `json:"method,omitempty"`

	// Provider The VPN provider, or an empty string for an unattributed range.
	//
	// Example: mullvad
	Provider *string `json:"provider,omitempty"`
}

// NotAvailable defines model for NotAvailable.
type NotAvailable = Error

// NotLicensed defines model for NotLicensed.
type NotLicensed = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// UnknownDataset defines model for UnknownDataset.
type UnknownDataset = Error

// DatabaseChecksumParams defines parameters for DatabaseChecksum.
type DatabaseChecksumParams struct {
	ID     string                       `form:"id" json:"id"`
	Format DatabaseChecksumParamsFormat `form:"format" json:"format"`
}

// DatabaseChecksumParamsFormat defines parameters for DatabaseChecksum.
type DatabaseChecksumParamsFormat string

// DownloadDatabaseParams defines parameters for DownloadDatabase.
type DownloadDatabaseParams struct {
	// ID Dataset id, e.g. vpn_ip_extended_v1
	ID string `form:"id" json:"id"`

	// Format Not every dataset is built in every format. The `_provider`
	// catalogues are keyed by provider id rather than by IP range, so no
	// MMDB exists for them.
	Format DownloadDatabaseParamsFormat `form:"format" json:"format"`
}

// DownloadDatabaseParamsFormat defines parameters for DownloadDatabase.
type DownloadDatabaseParamsFormat string

// ListDownloadsParams defines parameters for ListDownloads.
type ListDownloadsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatabaseMetadataParams defines parameters for DatabaseMetadata.
type DatabaseMetadataParams struct {
	ID string `form:"id" json:"id"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// DatabaseChecksum Checksums
	//
	// Checksums for one published file, so a download can be verified after it lands.
	//
	// Corresponds with GET /api/v1/database/checksum (the `DatabaseChecksum` operationId).
	DatabaseChecksum(ctx context.Context, params *DatabaseChecksumParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DownloadDatabase Download
	//
	// Answers `302` with a time-limited URL pointing straight at object storage. Follow the redirect; the link authorizes the START of a transfer, so one already running is not interrupted when it lapses.
	//
	// Corresponds with GET /api/v1/database/download (the `DownloadDatabase` operationId).
	DownloadDatabase(ctx context.Context, params *DownloadDatabaseParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDownloads History
	//
	// Recent download attempts for this organization, newest first. Refusals are listed too, so a failed transfer can be accounted for.
	//
	// Corresponds with GET /api/v1/database/downloads (the `ListDownloads` operationId).
	ListDownloads(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDatabases List
	//
	// Every dataset this organization holds a licence for, with the term and the license_type right beside each one.
	//
	// Corresponds with GET /api/v1/database/list (the `ListDatabases` operationId).
	ListDatabases(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatabaseMetadata Metadata
	//
	// Poll this to decide whether today's build is worth fetching: it carries
	// `updated` and `entries` without downloading anything.
	//
	// No `format` parameter - one document describes every format the dataset
	// is built in.
	//
	// Corresponds with GET /api/v1/database/metadata (the `DatabaseMetadata` operationId).
	DatabaseMetadata(ctx context.Context, params *DatabaseMetadataParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LookupIP Lookup
	//
	// Answers what is known about a single IPv4 or IPv6 address. Which fields
	// come back is decided by the plan behind the presented key; with no key
	// the answer is `ip` and `is_vpn`.
	//
	// Corresponds with GET /{ip} (the `LookupIP` operationId).
	LookupIP(ctx context.Context, ip string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// DatabaseChecksum Checksums
//
// Checksums for one published file, so a download can be verified after it lands.
//
// Corresponds with GET /api/v1/database/checksum (the `DatabaseChecksum` operationId).
func (c *Client) DatabaseChecksum(ctx context.Context, params *DatabaseChecksumParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatabaseChecksumRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DownloadDatabase Download
//
// Answers `302` with a time-limited URL pointing straight at object storage. Follow the redirect; the link authorizes the START of a transfer, so one already running is not interrupted when it lapses.
//
// Corresponds with GET /api/v1/database/download (the `DownloadDatabase` operationId).
func (c *Client) DownloadDatabase(ctx context.Context, params *DownloadDatabaseParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDownloadDatabaseRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDownloads History
//
// Recent download attempts for this organization, newest first. Refusals are listed too, so a failed transfer can be accounted for.
//
// Corresponds with GET /api/v1/database/downloads (the `ListDownloads` operationId).
func (c *Client) ListDownloads(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDownloadsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListDatabases List
//
// Every dataset this organization holds a licence for, with the term and the license_type right beside each one.
//
// Corresponds with GET /api/v1/database/list (the `ListDatabases` operationId).
func (c *Client) ListDatabases(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDatabasesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DatabaseMetadata Metadata
//
// Poll this to decide whether today's build is worth fetching: it carries
// `updated` and `entries` without downloading anything.
//
// No `format` parameter - one document describes every format the dataset
// is built in.
//
// Corresponds with GET /api/v1/database/metadata (the `DatabaseMetadata` operationId).
func (c *Client) DatabaseMetadata(ctx context.Context, params *DatabaseMetadataParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatabaseMetadataRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// LookupIP Lookup
//
// Answers what is known about a single IPv4 or IPv6 address. Which fields
// come back is decided by the plan behind the presented key; with no key
// the answer is `ip` and `is_vpn`.
//
// Corresponds with GET /{ip} (the `LookupIP` operationId).
func (c *Client) LookupIP(ctx context.Context, ip string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLookupIPRequest(c.Server, ip)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDatabaseChecksumRequest constructs an http.Request for the DatabaseChecksum method
func NewDatabaseChecksumRequest(server string, params *DatabaseChecksumParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/database/checksum")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDownloadDatabaseRequest constructs an http.Request for the DownloadDatabase method
func NewDownloadDatabaseRequest(server string, params *DownloadDatabaseParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/database/download")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDownloadsRequest constructs an http.Request for the ListDownloads method
func NewListDownloadsRequest(server string, params *ListDownloadsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/database/downloads")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDatabasesRequest constructs an http.Request for the ListDatabases method
func NewListDatabasesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/database/list")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatabaseMetadataRequest constructs an http.Request for the DatabaseMetadata method
func NewDatabaseMetadataRequest(server string, params *DatabaseMetadataParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/database/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", params.ID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLookupIPRequest constructs an http.Request for the LookupIP method
func NewLookupIPRequest(server string, ip string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "ip", ip, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// DatabaseChecksumWithResponse Checksums
	//
	// Checksums for one published file, so a download can be verified after it lands.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/database/checksum (the `DatabaseChecksum` operationId).
	DatabaseChecksumWithResponse(ctx context.Context, params *DatabaseChecksumParams, reqEditors ...RequestEditorFn) (*DatabaseChecksumResponse, error)

	// DownloadDatabaseWithResponse Download
	//
	// Answers `302` with a time-limited URL pointing straight at object storage. Follow the redirect; the link authorizes the START of a transfer, so one already running is not interrupted when it lapses.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/database/download (the `DownloadDatabase` operationId).
	DownloadDatabaseWithResponse(ctx context.Context, params *DownloadDatabaseParams, reqEditors ...RequestEditorFn) (*DownloadDatabaseResponse, error)

	// ListDownloadsWithResponse History
	//
	// Recent download attempts for this organization, newest first. Refusals are listed too, so a failed transfer can be accounted for.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/database/downloads (the `ListDownloads` operationId).
	ListDownloadsWithResponse(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*ListDownloadsResponse, error)

	// ListDatabasesWithResponse List
	//
	// Every dataset this organization holds a licence for, with the term and the license_type right beside each one.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/database/list (the `ListDatabases` operationId).
	ListDatabasesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDatabasesResponse, error)

	// DatabaseMetadataWithResponse Metadata
	//
	// Poll this to decide whether today's build is worth fetching: it carries
	// `updated` and `entries` without downloading anything.
	//
	// No `format` parameter - one document describes every format the dataset
	// is built in.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/database/metadata (the `DatabaseMetadata` operationId).
	DatabaseMetadataWithResponse(ctx context.Context, params *DatabaseMetadataParams, reqEditors ...RequestEditorFn) (*DatabaseMetadataResponse, error)

	// LookupIPWithResponse Lookup
	//
	// Answers what is known about a single IPv4 or IPv6 address. Which fields
	// come back is decided by the plan behind the presented key; with no key
	// the answer is `ip` and `is_vpn`.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /{ip} (the `LookupIP` operationId).
	LookupIPWithResponse(ctx context.Context, ip string, reqEditors ...RequestEditorFn) (*LookupIPResponse, error)
}

type DatabaseChecksumResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		// Checksums The published digests for one database file.
		Checksums DBChecksums `json:"checksums"`
		Format    string      `json:"format"`
		ID        string      `json:"id"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *NotLicensed
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *UnknownDataset
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *NotAvailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DatabaseChecksumResponse) GetJSON200() *struct {
	// Checksums The published digests for one database file.
	Checksums DBChecksums `json:"checksums"`
	Format    string      `json:"format"`
	ID        string      `json:"id"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DatabaseChecksumResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DatabaseChecksumResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DatabaseChecksumResponse) GetJSON403() *NotLicensed {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DatabaseChecksumResponse) GetJSON404() *UnknownDataset {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DatabaseChecksumResponse) GetJSON503() *NotAvailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DatabaseChecksumResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DatabaseChecksumResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatabaseChecksumResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatabaseChecksumResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DownloadDatabaseResponse302Headers the declared response headers of an HTTP 302 response for DownloadDatabase
type DownloadDatabaseResponse302Headers struct {
	Location *string
}

type DownloadDatabaseResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
	// Headers302 the parsed response headers for an HTTP 302 response
	Headers302 *DownloadDatabaseResponse302Headers
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DownloadDatabaseResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DownloadDatabaseResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DownloadDatabaseResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DownloadDatabaseResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DownloadDatabaseResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DownloadDatabaseResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DownloadDatabaseResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DownloadDatabaseResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DownloadDatabaseResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDownloadsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Downloads []Download `json:"downloads"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDownloadsResponse) GetJSON200() *struct {
	Downloads []Download `json:"downloads"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListDownloadsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListDownloadsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDownloadsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDownloadsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDownloadsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDatabasesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Databases []Database `json:"databases"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDatabasesResponse) GetJSON200() *struct {
	Databases []Database `json:"databases"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListDatabasesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListDatabasesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDatabasesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDatabasesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDatabasesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatabaseMetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DatabaseMetadata
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *NotLicensed
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *UnknownDataset
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *NotAvailable
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DatabaseMetadataResponse) GetJSON200() *DatabaseMetadata {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DatabaseMetadataResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DatabaseMetadataResponse) GetJSON403() *NotLicensed {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DatabaseMetadataResponse) GetJSON404() *UnknownDataset {
	return r.JSON404
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r DatabaseMetadataResponse) GetJSON503() *NotAvailable {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r DatabaseMetadataResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DatabaseMetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatabaseMetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatabaseMetadataResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// LookupIPResponse429Headers the declared response headers of an HTTP 429 response for LookupIP
type LookupIPResponse429Headers struct {
	RetryAfter *int
}

type LookupIPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LookupResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *LookupError
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *LookupError
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *LookupError
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *LookupError
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *LookupError
	// Headers429 the parsed response headers for an HTTP 429 response
	Headers429 *LookupIPResponse429Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r LookupIPResponse) GetJSON200() *LookupResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r LookupIPResponse) GetJSON400() *LookupError {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r LookupIPResponse) GetJSON401() *LookupError {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r LookupIPResponse) GetJSON403() *LookupError {
	return r.JSON403
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r LookupIPResponse) GetJSON429() *LookupError {
	return r.JSON429
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r LookupIPResponse) GetJSON500() *LookupError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r LookupIPResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r LookupIPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LookupIPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r LookupIPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DatabaseChecksumWithResponse Checksums
//
// Checksums for one published file, so a download can be verified after it lands.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/database/checksum (the `DatabaseChecksum` operationId).
func (c *ClientWithResponses) DatabaseChecksumWithResponse(ctx context.Context, params *DatabaseChecksumParams, reqEditors ...RequestEditorFn) (*DatabaseChecksumResponse, error) {
	rsp, err := c.DatabaseChecksum(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatabaseChecksumResponse(rsp)
}

// DownloadDatabaseWithResponse Download
//
// Answers `302` with a time-limited URL pointing straight at object storage. Follow the redirect; the link authorizes the START of a transfer, so one already running is not interrupted when it lapses.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/database/download (the `DownloadDatabase` operationId).
func (c *ClientWithResponses) DownloadDatabaseWithResponse(ctx context.Context, params *DownloadDatabaseParams, reqEditors ...RequestEditorFn) (*DownloadDatabaseResponse, error) {
	rsp, err := c.DownloadDatabase(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDownloadDatabaseResponse(rsp)
}

// ListDownloadsWithResponse History
//
// Recent download attempts for this organization, newest first. Refusals are listed too, so a failed transfer can be accounted for.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/database/downloads (the `ListDownloads` operationId).
func (c *ClientWithResponses) ListDownloadsWithResponse(ctx context.Context, params *ListDownloadsParams, reqEditors ...RequestEditorFn) (*ListDownloadsResponse, error) {
	rsp, err := c.ListDownloads(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDownloadsResponse(rsp)
}

// ListDatabasesWithResponse List
//
// Every dataset this organization holds a licence for, with the term and the license_type right beside each one.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/database/list (the `ListDatabases` operationId).
func (c *ClientWithResponses) ListDatabasesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDatabasesResponse, error) {
	rsp, err := c.ListDatabases(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDatabasesResponse(rsp)
}

// DatabaseMetadataWithResponse Metadata
//
// Poll this to decide whether today's build is worth fetching: it carries
// `updated` and `entries` without downloading anything.
//
// No `format` parameter - one document describes every format the dataset
// is built in.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/database/metadata (the `DatabaseMetadata` operationId).
func (c *ClientWithResponses) DatabaseMetadataWithResponse(ctx context.Context, params *DatabaseMetadataParams, reqEditors ...RequestEditorFn) (*DatabaseMetadataResponse, error) {
	rsp, err := c.DatabaseMetadata(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatabaseMetadataResponse(rsp)
}

// LookupIPWithResponse Lookup
//
// Answers what is known about a single IPv4 or IPv6 address. Which fields
// come back is decided by the plan behind the presented key; with no key
// the answer is `ip` and `is_vpn`.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /{ip} (the `LookupIP` operationId).
func (c *ClientWithResponses) LookupIPWithResponse(ctx context.Context, ip string, reqEditors ...RequestEditorFn) (*LookupIPResponse, error) {
	rsp, err := c.LookupIP(ctx, ip, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLookupIPResponse(rsp)
}

// ParseDatabaseChecksumResponse parses an HTTP response from a DatabaseChecksumWithResponse call
func ParseDatabaseChecksumResponse(rsp *http.Response) (*DatabaseChecksumResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatabaseChecksumResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Checksums The published digests for one database file.
			Checksums DBChecksums `json:"checksums"`
			Format    string      `json:"format"`
			ID        string      `json:"id"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest NotLicensed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UnknownDataset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest NotAvailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseDownloadDatabaseResponse parses an HTTP response from a DownloadDatabaseWithResponse call
func ParseDownloadDatabaseResponse(rsp *http.Response) (*DownloadDatabaseResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DownloadDatabaseResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 302:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	switch {
	case rsp.StatusCode == 302:
		var headers DownloadDatabaseResponse302Headers
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		response.Headers302 = &headers
	}

	return response, nil
}

// ParseListDownloadsResponse parses an HTTP response from a ListDownloadsWithResponse call
func ParseListDownloadsResponse(rsp *http.Response) (*ListDownloadsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDownloadsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Downloads []Download `json:"downloads"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseListDatabasesResponse parses an HTTP response from a ListDatabasesWithResponse call
func ParseListDatabasesResponse(rsp *http.Response) (*ListDatabasesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDatabasesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Databases []Database `json:"databases"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseDatabaseMetadataResponse parses an HTTP response from a DatabaseMetadataWithResponse call
func ParseDatabaseMetadataResponse(rsp *http.Response) (*DatabaseMetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatabaseMetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatabaseMetadata
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest NotLicensed
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest UnknownDataset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest NotAvailable
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseLookupIPResponse parses an HTTP response from a LookupIPWithResponse call
func ParseLookupIPResponse(rsp *http.Response) (*LookupIPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LookupIPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LookupResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest LookupError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest LookupError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest LookupError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest LookupError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest LookupError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 429:
		var headers LookupIPResponse429Headers
		if values := rsp.Header.Values("Retry-After"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "Retry-After", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.RetryAfter = &value
		}
		response.Headers429 = &headers
	}

	return response, nil
}
